# Generated by Django 5.2.5 on 2025-08-20 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_calendar_id', models.CharField(max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_token', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('sync_direction', models.CharField(choices=[('to_google', 'To Google Only'), ('from_google', 'From Google Only'), ('bidirectional', 'Bidirectional')], default='bidirectional', max_length=20)),
                ('calendar_name', models.CharField(blank=True, max_length=255, null=True)),
                ('calendar_description', models.TextField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('events_synced', models.PositiveIntegerField(default=0)),
                ('appointments_created', models.PositiveIntegerField(default=0)),
                ('appointments_updated', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_sync', to='core.workspace')),
            ],
            options={
                'db_table': 'google_calendar_syncs',
                'ordering': ['-last_sync_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Customer Appointment', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_calendar_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_meet_link', models.URLField(blank=True, null=True)),
                ('location_type', models.CharField(choices=[('in_person', 'In Person'), ('video_call', 'Video Call'), ('phone_call', 'Phone Call')], default='video_call', max_length=20)),
                ('location_details', models.TextField(blank=True, help_text='Address or meeting link', null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('email_reminder', models.BooleanField(default=True)),
                ('reminder_minutes_before', models.IntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.workspace')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['workspace', 'start_time'], name='appointment_workspa_e15760_idx'), models.Index(fields=['status', 'start_time'], name='appointment_status_12e0f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('max_bookings', models.PositiveIntegerField(default=1)),
                ('current_bookings', models.PositiveIntegerField(default=0)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='core.workspace')),
            ],
            options={
                'db_table': 'availability_slots',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['workspace', 'start_time', 'is_available'], name='availabilit_workspa_bc2794_idx')],
            },
        ),
    ]
