# Generated by Django 5.2.5 on 2025-08-21 17:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_workspace_owner_appuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('context_change', 'Context Field Changed'), ('new_message', 'New Message Received'), ('status_change', 'Status Changed'), ('priority_change', 'Priority Changed'), ('time_elapsed', 'Time Elapsed'), ('completion_rate', 'Completion Rate Changed'), ('sentiment_change', 'Sentiment Changed')], max_length=30)),
                ('trigger_conditions', models.JSONField(default=dict, help_text='Conditions that must be met')),
                ('actions', models.JSONField(default=list, help_text='Actions to execute when triggered')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100, help_text='Lower numbers = higher priority')),
                ('execution_count', models.IntegerField(default=0)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('success_rate', models.FloatField(default=1.0, help_text='Percentage of successful executions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rules', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_rules', to='core.workspace')),
            ],
            options={
                'db_table': 'business_rules',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConversationContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Auto-generated or manual title', max_length=255)),
                ('context_data', models.JSONField(default=dict, help_text='Field values based on schema')),
                ('ai_confidence_scores', models.JSONField(default=dict, help_text='AI confidence per field')),
                ('status', models.CharField(default='new', help_text='Current status from schema', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('tags', models.JSONField(default=list, help_text='Array of tags')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_ai_update', models.DateTimeField(blank=True, null=True)),
                ('last_human_update', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_context', to='core.conversation')),
            ],
            options={
                'db_table': 'conversation_contexts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContextHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('created', 'Context Created'), ('field_updated', 'Field Updated'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('ai_updated', 'AI Updated'), ('schema_changed', 'Schema Changed'), ('bulk_update', 'Bulk Update')], max_length=20)),
                ('field_name', models.CharField(blank=True, help_text='Which field changed', max_length=100)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('changed_by_ai', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(blank=True, help_text='AI confidence if AI change', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='context_tracking.conversationcontext')),
            ],
            options={
                'db_table': 'context_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(max_length=30)),
                ('trigger_data', models.JSONField(default=dict)),
                ('execution_result', models.JSONField(default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time', models.FloatField(help_text='Execution time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_executions', to='context_tracking.conversationcontext')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='context_tracking.businessrule')),
            ],
            options={
                'db_table': 'rule_executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceContextSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Schema name (e.g., 'Real Estate Inquiries')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='What this schema tracks')),
                ('fields', models.JSONField(default=list, help_text='Array of field definitions')),
                ('status_workflow', models.JSONField(default=dict, help_text='Custom status definitions and transitions')),
                ('priority_config', models.JSONField(default=dict, help_text='Priority calculation configuration')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default schema for new conversations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schemas', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_schemas', to='core.workspace')),
            ],
            options={
                'db_table': 'workspace_context_schemas',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='context_tracking.workspacecontextschema'),
        ),
        migrations.AddIndex(
            model_name='businessrule',
            index=models.Index(fields=['workspace', 'is_active'], name='business_ru_workspa_82a4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='businessrule',
            index=models.Index(fields=['trigger_type', 'is_active'], name='business_ru_trigger_8f7bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='businessrule',
            index=models.Index(fields=['priority'], name='business_ru_priorit_f4560d_idx'),
        ),
        migrations.AddIndex(
            model_name='contexthistory',
            index=models.Index(fields=['context', '-created_at'], name='context_his_context_eb497a_idx'),
        ),
        migrations.AddIndex(
            model_name='contexthistory',
            index=models.Index(fields=['action_type', '-created_at'], name='context_his_action__f5282a_idx'),
        ),
        migrations.AddIndex(
            model_name='contexthistory',
            index=models.Index(fields=['changed_by_ai', '-created_at'], name='context_his_changed_10d1ef_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleexecution',
            index=models.Index(fields=['rule', '-created_at'], name='rule_execut_rule_id_91842b_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleexecution',
            index=models.Index(fields=['context', '-created_at'], name='rule_execut_context_5bc7bd_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleexecution',
            index=models.Index(fields=['success', '-created_at'], name='rule_execut_success_6ed6da_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacecontextschema',
            index=models.Index(fields=['workspace', 'is_active'], name='workspace_c_workspa_289053_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacecontextschema',
            index=models.Index(fields=['workspace', 'is_default'], name='workspace_c_workspa_7006bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacecontextschema',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='conversationcontext',
            index=models.Index(fields=['schema', 'status'], name='conversatio_schema__a38bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationcontext',
            index=models.Index(fields=['schema', 'priority'], name='conversatio_schema__841ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationcontext',
            index=models.Index(fields=['conversation'], name='conversatio_convers_a6e4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationcontext',
            index=models.Index(fields=['-updated_at'], name='conversatio_updated_470aa2_idx'),
        ),
    ]
