# Generated by Django 5.1.5 on 2025-08-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrule',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Whether this is a default system rule'),
        ),
    ]
