# Generated by Django 5.1.5 on 2025-08-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_tracking', '0002_businessrule_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrule',
            name='average_execution_time',
            field=models.FloatField(default=0.0, help_text='Average execution time in seconds'),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='execution_interval',
            field=models.IntegerField(default=0, help_text='Minimum seconds between executions'),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='external_conditions',
            field=models.JSONField(default=dict, help_text='External system conditions'),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='field_dependencies',
            field=models.JSONField(default=dict, help_text='Field dependency rules'),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Whether this rule can be used as a template'),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='last_execution_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='max_executions',
            field=models.IntegerField(default=0, help_text='Maximum executions (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='rollback_actions',
            field=models.JSONField(default=list, help_text='Actions to execute on failure'),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='rule_version',
            field=models.CharField(default='1.0', help_text='Version of the rule', max_length=20),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='success_threshold',
            field=models.FloatField(default=0.8, help_text='Minimum success rate to keep rule active'),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='template_category',
            field=models.CharField(blank=True, help_text='Category for rule templates', max_length=100),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='time_conditions',
            field=models.JSONField(default=dict, help_text='Time-based conditions (business hours, etc.)'),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='workflow_steps',
            field=models.JSONField(default=list, help_text='Multi-step workflow configuration'),
        ),
        migrations.AlterField(
            model_name='businessrule',
            name='trigger_type',
            field=models.CharField(choices=[('context_change', 'Context Field Changed'), ('new_message', 'New Message Received'), ('status_change', 'Status Changed'), ('priority_change', 'Priority Changed'), ('time_elapsed', 'Time Elapsed'), ('completion_rate', 'Completion Rate Changed'), ('sentiment_change', 'Sentiment Changed'), ('field_dependency', 'Field Dependency Met'), ('schedule', 'Scheduled Trigger'), ('external_webhook', 'External Webhook Trigger'), ('conversation_age', 'Conversation Age Threshold'), ('response_time', 'Response Time Threshold'), ('customer_satisfaction', 'Customer Satisfaction Score'), ('business_hours', 'Business Hours Check'), ('workload_balance', 'Workload Distribution')], max_length=30),
        ),
    ]
