# Generated by Django 5.1.5 on 2025-08-23 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_tracking', '0003_businessrule_average_execution_time_and_more'),
        ('core', '0003_workspace_owner_appuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFieldSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggested_field_name', models.CharField(help_text='Name of the suggested field', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('decimal', 'Decimal'), ('date', 'Date'), ('datetime', 'Date & Time'), ('boolean', 'Yes/No'), ('choice', 'Choice Dropdown'), ('multi_choice', 'Multi-Select'), ('email', 'Email'), ('phone', 'Phone Number'), ('url', 'URL'), ('tags', 'Tags'), ('priority', 'Priority Level'), ('status', 'Status')], help_text='Data type for the field', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of what this field captures')),
                ('frequency_detected', models.IntegerField(default=1, help_text='How many times this pattern was detected')),
                ('sample_values', models.JSONField(default=list, help_text='Sample values found for this field')),
                ('confidence_score', models.FloatField(help_text='AI confidence in this suggestion (0.0-1.0)')),
                ('business_value_score', models.FloatField(default=0.0, help_text='Estimated business value of this field (0.0-1.0)')),
                ('detection_pattern', models.TextField(blank=True, help_text='Pattern or context where this field was detected')),
                ('related_fields', models.JSONField(default=list, help_text='Other fields that often appear with this one')),
                ('context_examples', models.JSONField(default=list, help_text='Example conversation contexts where this field appears')),
                ('is_reviewed', models.BooleanField(default=False, help_text='Whether user has reviewed this suggestion')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether user approved this suggestion')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the suggestion was reviewed', null=True)),
                ('review_notes', models.TextField(blank=True, help_text='User notes about this suggestion')),
                ('implemented_at', models.DateTimeField(blank=True, help_text='When this suggestion was implemented', null=True)),
                ('implementation_notes', models.TextField(blank=True, help_text='Notes about how this field was implemented')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to=settings.AUTH_USER_MODEL)),
                ('target_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implemented_suggestions', to='context_tracking.workspacecontextschema')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_suggestions', to='core.workspace')),
            ],
            options={
                'db_table': 'dynamic_field_suggestions',
                'ordering': ['-confidence_score', '-business_value_score', '-frequency_detected'],
                'indexes': [models.Index(fields=['workspace', 'is_reviewed'], name='dynamic_fie_workspa_d679a0_idx'), models.Index(fields=['workspace', 'is_approved'], name='dynamic_fie_workspa_eb14a2_idx'), models.Index(fields=['confidence_score', '-created_at'], name='dynamic_fie_confide_79e35e_idx'), models.Index(fields=['business_value_score', '-created_at'], name='dynamic_fie_busines_921685_idx')],
            },
        ),
    ]
