# Generated by Django 4.2.23 on 2025-08-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='ai_personality',
            field=models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('formal', 'Formal'), ('casual', 'Casual'), ('empathetic', 'Empathetic'), ('direct', 'Direct')], default='professional', max_length=100),
        ),
        migrations.AddField(
            model_name='workspace',
            name='ai_role',
            field=models.CharField(choices=[('general', 'General Assistant'), ('banker', 'Banking Assistant'), ('medical', 'Medical Assistant'), ('legal', 'Legal Assistant'), ('real_estate', 'Real Estate Assistant'), ('restaurant', 'Restaurant Assistant'), ('retail', 'Retail Assistant'), ('tech_support', 'Technical Support'), ('secretary', 'Personal Secretary'), ('customer_service', 'Customer Service'), ('consultant', 'Business Consultant'), ('educator', 'Educational Assistant')], default='general', max_length=100),
        ),
        migrations.AddField(
            model_name='workspace',
            name='custom_instructions',
            field=models.TextField(blank=True, help_text='Custom instructions for AI behavior', null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='owner_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
