# Generated by Django 5.1.5 on 2025-08-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_ai_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstypetemplate',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='Number of times this template has been applied'),
        ),
    ]
