# Generated by Django 5.1.5 on 2025-08-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_businesstypetemplate_usage_count'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(
                fields=['session', 'status'],
                condition=models.Q(status='active'),
                name='unique_active_conversation_per_session'
            ),
        ),
    ]
