# Generated by Django 5.1.5 on 2025-08-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250823_2344'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='unique_active_conversation_per_session',
        ),
    ]
