# Generated by Django 5.2.5 on 2025-08-20 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('client', 'Client'), ('assistant', 'AI Assistant'), ('owner', 'Business Owner')], max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('audio', 'Audio Message'), ('file', 'File Attachment'), ('system', 'System Message')], default='text', max_length=20)),
                ('status', models.CharField(choices=[('sending', 'Sending'), ('sent', 'Sent'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('text', models.TextField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('media_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('media_size', models.PositiveIntegerField(blank=True, null=True)),
                ('intent_classification', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioTranscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcribed_text', models.TextField()),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='messaging.message')),
            ],
            options={
                'db_table': 'audio_transcriptions',
            },
        ),
        migrations.CreateModel(
            name='MessageDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggested_text', models.TextField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('context_sources', models.JSONField(blank=True, default=list)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_messages', to='core.conversation')),
            ],
            options={
                'db_table': 'message_drafts',
                'ordering': ['-created_at'],
            },
        ),
    ]
